### ISSUE TITLE
sweeny.js feels icky, can this be a dotfile?

### ISSUE THREAD

**Issue by dmikey** [gabrielcsapo/sweeney#1]
`.sweenycfg` or `.sweenyrc` ?

**Comment by gabrielcsapo** [comment]
the dot file would still be considered a javascript file correct?

You could have:

```
module.exports = {};
``` 

as the contents?

**Comment by gabrielcsapo** [comment]
@dmikey I have an implementation here https://github.com/gabrielcsapo/sweeney/pull/2 if you could review it
