### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by karanrajpal14** [gabrielcsapo/sweeney#3]
I'd like to know more about this but the [site](https://wwww.gabrielcsapo.com/sweeney) seems to be down? Would you please look into it?

**Comment by gabrielcsapo** [comment]
Fixed the link in the readme, it should be https://www.gabrielcsapo.com/sweeney. Let me know if that works for you!

**Comment by karanrajpal14** [comment]
Yep. Works great! Will give this a whirl later on. Thank you!
